---
http_interactions:
- request:
    method: get
    uri: https://login.microsoftonline.com/<AZURE_TENANT_ID>/oauth2/token
    body:
      encoding: UTF-8
      string: resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id=<AZURE_CLIENT_ID>&client_secret=<AZURE_CLIENT_SECRET>&grant_type=client_credentials
    headers:
      User-Agent:
      - Faraday v0.9.2
      content-type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache, no-store
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      server:
      - Microsoft-IIS/8.5
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      x-content-type-options:
      - nosniff
      client-request-id:
      - 6d1b6170-4df1-41ee-98c9-deba39cfecde
      x-ms-request-id:
      - e1a6e267-de17-4751-a5d5-dad243a7cbf4
      p3p:
      - CP="DSP CUR OTPi IND OTRi ONL FIN"
      set-cookie:
      - esctx=AQABAAAAAADRNYRQ3dhRSrm-4K-adpCJ8eFRQUipL-YT5cNF6MQ0lxZyvEpnXkU8yburC2qQ0woqtuTis0FyLeWN-W0edkovXtyIgJzKqJ3Ej3jec4KBHAQ2NQhFITijkto-qcEMtAqa1Tre0Yiptfckrt-FfxflrQ88We_1p9Uc40LfVV2B6pw7Mtls3AnpfixGfqbHnnEgAA;
        domain=.login.microsoftonline.com; path=/; secure; HttpOnly, x-ms-gateway-slice=productionb;
        path=/; secure; HttpOnly, stsservicecookie=ests; path=/; secure; HttpOnly
      x-powered-by:
      - ASP.NET
      date:
      - Tue, 27 Sep 2016 20:56:26 GMT
      connection:
      - close
      content-length:
      - '1255'
    body:
      encoding: UTF-8
      string: '{"token_type":"Bearer","expires_in":"3599","ext_expires_in":"0","expires_on":"1475013387","not_before":"1475009487","resource":"https://management.core.windows.net/","access_token":"<ACCESS_TOKEN>"}'
    http_version: 
  recorded_at: Tue, 27 Sep 2016 20:56:27 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/falling-dust-38?api-version=2016-02-01
    body:
      encoding: UTF-8
      string: '{"location":"westus"}'
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.5.0/
      x-ms-client-request-id:
      - 6668c32e-86c7-4aba-a235-8a7947dc350b
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-length:
      - '183'
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-writes:
      - '1199'
      x-ms-request-id:
      - b88a66e0-2848-42dd-b314-ca6db55b49d4
      x-ms-correlation-request-id:
      - b88a66e0-2848-42dd-b314-ca6db55b49d4
      x-ms-routing-request-id:
      - WESTUS2:20160927T205628Z:b88a66e0-2848-42dd-b314-ca6db55b49d4
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Tue, 27 Sep 2016 20:56:28 GMT
      connection:
      - close
    body:
      encoding: UTF-8
      string: '{"id":"/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourceGroups/falling-dust-38","name":"falling-dust-38","location":"westus","properties":{"provisioningState":"Succeeded"}}'
    http_version: 
  recorded_at: Tue, 27 Sep 2016 20:56:28 GMT
- request:
    method: put
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/falling-dust-38/providers/Microsoft.Resources/deployments/azure-sample?api-version=2016-02-01
    body:
      encoding: UTF-8
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.5.0/
      x-ms-client-request-id:
      - 3c9ced2f-3846-42ad-b7b8-4ebd2415c695
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 201
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      azure-asyncoperation:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/falling-dust-38/providers/Microsoft.Resources/deployments/azure-sample/operationStatuses/08587265970966310302?api-version=2016-02-01
      x-ms-ratelimit-remaining-subscription-writes:
      - '1199'
      x-ms-request-id:
      - 0bbc1df1-0220-4251-9dbe-ff68a95b5083
      x-ms-correlation-request-id:
      - 0bbc1df1-0220-4251-9dbe-ff68a95b5083
      x-ms-routing-request-id:
      - WESTUS2:20160927T205629Z:0bbc1df1-0220-4251-9dbe-ff68a95b5083
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Tue, 27 Sep 2016 20:56:29 GMT
      connection:
      - close
      content-length:
      - '4086'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 27 Sep 2016 20:56:29 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/falling-dust-38/providers/Microsoft.Resources/deployments/azure-sample/operationStatuses/08587265970966310302?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      x-ms-client-request-id:
      - 3c9ced2f-3846-42ad-b7b8-4ebd2415c695
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
      User-Agent:
      - Azure-SDK-For-Ruby/0.5.0/
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14994'
      x-ms-request-id:
      - 57f4c9a8-8b11-4ba1-8bde-8e93104d4f1f
      x-ms-correlation-request-id:
      - 57f4c9a8-8b11-4ba1-8bde-8e93104d4f1f
      x-ms-routing-request-id:
      - WESTUS2:20160927T205659Z:57f4c9a8-8b11-4ba1-8bde-8e93104d4f1f
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Tue, 27 Sep 2016 20:56:58 GMT
      connection:
      - close
      content-length:
      - '140'
    body:
      encoding: ASCII-8BIT
      string: '{"status":"Running"}'
    http_version: 
  recorded_at: Tue, 27 Sep 2016 20:56:59 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/falling-dust-38/providers/Microsoft.Resources/deployments/azure-sample/operationStatuses/08587265970966310302?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      x-ms-client-request-id:
      - 3c9ced2f-3846-42ad-b7b8-4ebd2415c695
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
      User-Agent:
      - Azure-SDK-For-Ruby/0.5.0/
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14998'
      x-ms-request-id:
      - d84307ea-fc81-4df2-9540-518340b970c6
      x-ms-correlation-request-id:
      - d84307ea-fc81-4df2-9540-518340b970c6
      x-ms-routing-request-id:
      - WESTUS2:20160927T205730Z:d84307ea-fc81-4df2-9540-518340b970c6
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Tue, 27 Sep 2016 20:57:30 GMT
      connection:
      - close
      content-length:
      - '140'
    body:
      encoding: ASCII-8BIT
      string: '{"status":"Running"}'
    http_version: 
  recorded_at: Tue, 27 Sep 2016 20:57:30 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/falling-dust-38/providers/Microsoft.Resources/deployments/azure-sample/operationStatuses/08587265970966310302?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      x-ms-client-request-id:
      - 3c9ced2f-3846-42ad-b7b8-4ebd2415c695
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
      User-Agent:
      - Azure-SDK-For-Ruby/0.5.0/
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14994'
      x-ms-request-id:
      - 7a5b82e6-beb8-4ecc-ade5-fa0318496f69
      x-ms-correlation-request-id:
      - 7a5b82e6-beb8-4ecc-ade5-fa0318496f69
      x-ms-routing-request-id:
      - WESTUS2:20160927T205800Z:7a5b82e6-beb8-4ecc-ade5-fa0318496f69
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Tue, 27 Sep 2016 20:57:59 GMT
      connection:
      - close
      content-length:
      - '140'
    body:
      encoding: ASCII-8BIT
      string: '{"status":"Running"}'
    http_version: 
  recorded_at: Tue, 27 Sep 2016 20:58:00 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/falling-dust-38/providers/Microsoft.Resources/deployments/azure-sample/operationStatuses/08587265970966310302?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      x-ms-client-request-id:
      - 3c9ced2f-3846-42ad-b7b8-4ebd2415c695
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
      User-Agent:
      - Azure-SDK-For-Ruby/0.5.0/
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14996'
      x-ms-request-id:
      - 019a3968-35ce-4b8a-a0d8-b1ae4a238e7e
      x-ms-correlation-request-id:
      - 019a3968-35ce-4b8a-a0d8-b1ae4a238e7e
      x-ms-routing-request-id:
      - WESTUS2:20160927T205830Z:019a3968-35ce-4b8a-a0d8-b1ae4a238e7e
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Tue, 27 Sep 2016 20:58:30 GMT
      connection:
      - close
      content-length:
      - '140'
    body:
      encoding: ASCII-8BIT
      string: '{"status":"Running"}'
    http_version: 
  recorded_at: Tue, 27 Sep 2016 20:58:30 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/falling-dust-38/providers/Microsoft.Resources/deployments/azure-sample/operationStatuses/08587265970966310302?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      x-ms-client-request-id:
      - 3c9ced2f-3846-42ad-b7b8-4ebd2415c695
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
      User-Agent:
      - Azure-SDK-For-Ruby/0.5.0/
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14986'
      x-ms-request-id:
      - 0139010a-43a4-4f59-ad64-25e960418c2b
      x-ms-correlation-request-id:
      - 0139010a-43a4-4f59-ad64-25e960418c2b
      x-ms-routing-request-id:
      - WESTUS2:20160927T205900Z:0139010a-43a4-4f59-ad64-25e960418c2b
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Tue, 27 Sep 2016 20:59:00 GMT
      connection:
      - close
      content-length:
      - '140'
    body:
      encoding: ASCII-8BIT
      string: '{"status":"Running"}'
    http_version: 
  recorded_at: Tue, 27 Sep 2016 20:59:01 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/falling-dust-38/providers/Microsoft.Resources/deployments/azure-sample/operationStatuses/08587265970966310302?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      x-ms-client-request-id:
      - 3c9ced2f-3846-42ad-b7b8-4ebd2415c695
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
      User-Agent:
      - Azure-SDK-For-Ruby/0.5.0/
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14994'
      x-ms-request-id:
      - 36ee60d8-6819-4ce8-a5ca-8391202126ac
      x-ms-correlation-request-id:
      - 36ee60d8-6819-4ce8-a5ca-8391202126ac
      x-ms-routing-request-id:
      - WESTUS2:20160927T205931Z:36ee60d8-6819-4ce8-a5ca-8391202126ac
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Tue, 27 Sep 2016 20:59:30 GMT
      connection:
      - close
      content-length:
      - '141'
    body:
      encoding: ASCII-8BIT
      string: '{"status":"Succeeded"}'
    http_version: 
  recorded_at: Tue, 27 Sep 2016 20:59:31 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/falling-dust-38/providers/Microsoft.Resources/deployments/azure-sample?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.5.0/
      x-ms-client-request-id:
      - 3c9ced2f-3846-42ad-b7b8-4ebd2415c695
      accept-language:
      - en-US
      Content-Type:
      - application/json; charset=utf-8
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      content-type:
      - application/json; charset=utf-8
      expires:
      - "-1"
      vary:
      - Accept-Encoding
      x-ms-ratelimit-remaining-subscription-reads:
      - '14989'
      x-ms-request-id:
      - 89c15a74-ebf3-4e79-aa03-961b5dd87cac
      x-ms-correlation-request-id:
      - 89c15a74-ebf3-4e79-aa03-961b5dd87cac
      x-ms-routing-request-id:
      - WESTUS2:20160927T205931Z:89c15a74-ebf3-4e79-aa03-961b5dd87cac
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Tue, 27 Sep 2016 20:59:30 GMT
      connection:
      - close
      content-length:
      - '1535'
    body:
      encoding: ASCII-8BIT
      string: ''
    http_version: 
  recorded_at: Tue, 27 Sep 2016 20:59:31 GMT
- request:
    method: delete
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/resourcegroups/falling-dust-38?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      User-Agent:
      - Azure-SDK-For-Ruby/0.5.0/
      x-ms-client-request-id:
      - cee2b7c3-2bd1-48f6-803f-4d96f370efa8
      accept-language:
      - en-US
  response:
    status:
      code: 202
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      location:
      - https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1GQUxMSU5HOjJERFVTVDoyRDM4LVdFU1RVUyIsImpvYkxvY2F0aW9uIjoid2VzdHVzIn0?api-version=2016-02-01
      retry-after: '1'
      x-ms-ratelimit-remaining-subscription-writes:
      - '1198'
      x-ms-request-id:
      - f0db3649-db5c-40ce-b2b9-95b6f1bbd2f6
      x-ms-correlation-request-id:
      - f0db3649-db5c-40ce-b2b9-95b6f1bbd2f6
      x-ms-routing-request-id:
      - WESTUS2:20160927T205931Z:f0db3649-db5c-40ce-b2b9-95b6f1bbd2f6
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Tue, 27 Sep 2016 20:59:31 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 27 Sep 2016 20:59:31 GMT
- request:
    method: get
    uri: https://management.azure.com/subscriptions/<AZURE_SUBSCRIPTION_ID>/operationresults/eyJqb2JJZCI6IlJFU09VUkNFR1JPVVBERUxFVElPTkpPQi1GQUxMSU5HOjJERFVTVDoyRDM4LVdFU1RVUyIsImpvYkxvY2F0aW9uIjoid2VzdHVzIn0?api-version=2016-02-01
    body:
      encoding: US-ASCII
      string: ''
    headers:
      x-ms-client-request-id:
      - cee2b7c3-2bd1-48f6-803f-4d96f370efa8
      accept-language:
      - en-US
      User-Agent:
      - Azure-SDK-For-Ruby/0.5.0/
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: 
    headers:
      cache-control:
      - no-cache
      pragma:
      - no-cache
      expires:
      - "-1"
      x-ms-ratelimit-remaining-subscription-reads:
      - '14992'
      x-ms-request-id:
      - 27910529-f556-4fd5-8b42-98107802044a
      x-ms-correlation-request-id:
      - 27910529-f556-4fd5-8b42-98107802044a
      x-ms-routing-request-id:
      - WESTUS2:20160927T210636Z:27910529-f556-4fd5-8b42-98107802044a
      strict-transport-security:
      - max-age=31536000; includeSubDomains
      date:
      - Tue, 27 Sep 2016 21:06:36 GMT
      connection:
      - close
      content-length:
      - '0'
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 27 Sep 2016 21:06:36 GMT
recorded_with: VCR 3.0.3
